version: "3.3"
services:
  nginx-certbot:
    build:
      context: ./
    privileged: true
    restart: unless-stopped
    network_mode: host
    volumes:
      - './data/logs:/var/log/nginx'
      - './data/html:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './sites:/etc/nginx/conf.d'
      - './ssl:/etc/nginx/ssl/'
      - './letsencrypt/:/etc/letsencrypt/'
    environment:
#      - CERTBOT_DOMAINS=learntw.com
      - CERTBOT_EMAIL=pvq212@gmail.com
